# See [Jekyll Configuration](http://jekyllrb.com/docs/configuration/)

# Site Settings
#baseurl: &baseurl "/home/repos/github/dhurlburtusa/dhurlburtusa.github.io/tree/master/_site"
baseurl: &baseurl "https://dhurlburtusa.github.io"

description: >
  Dan Hurlburt, senior software developer, senior web application developer.
  Dan Hurlburt started learning HTML, CSS, and JavaScript over ten years ago.

exclude:
  - Gemfile
  - Gemfile.lock

gems:
  - jekyll-paginate
  # - jekyll-sitemap

link:
  angular_csp:
    base_path: *baseurl
    path: /static/js/angular-1.5.2/angular-csp.css
  blog:
    base_path: *baseurl
    path: /static/css/blog.css
  bootstrap:
    base_path: *baseurl
    path: /static/css/bootstrap-3.2.0-dist/css/bootstrap.css
  google_fonts_open_sans_400_700:
    href: https://fonts.googleapis.com/css?family=Open+Sans:400,700
  css_properties:
    base_path: *baseurl
    path: /static/css/css-properties-1.0.0/properties.css
  site:
    base_path: *baseurl
    path: /static/css/site.css

paginate: 10
paginate_path: "/blog/page:num/"

permalink: /blog/:year/:month/:day/:title/

excerpt_separator: <!-- stop excerpt -->

script:
  angular:
    base_path: *baseurl
    path: /static/js/angular-1.5.2/angular.min.js
  angular_animate:
    base_path: *baseurl
    path: /static/js/angular-1.5.2/angular-animate.min.js
  angular_resource:
    base_path: *baseurl
    path: /static/js/angular-1.5.2/angular-resource.min.js
  angular_sanitize:
    base_path: *baseurl
    path: /static/js/angular-1.5.2/angular-sanitize.min.js

timezone: America/Denver

title: Dan Hurlburt

# Default Page Settings

defaults:
  - 
    scope:
      path: ""
    values:
      doc:
        html:
          head:
            lang: en_US
            meta:
              http_equiv:
                X_UA_Compatible: IE=edge
              name:
                author: Danny Hurlburt
                viewport: width=device-width, initial-scale=1
            link:
              stylesheets:
                defaults:
                  - google_fonts_open_sans_400_700
                  - bootstrap
                  - css_properties
                  - site
  - 
    scope:
      path: blog
    values:
      doc:
        html:
          head:
            link:
              stylesheets:
                extras:
                  - blog
  - 
    scope:
      path: blog
      type: pages
    values:
      doc:
        html:
          head:
            base:
              href: *baseurl
            link:
              stylesheets:
                extras:
                  - angular_csp
                  - blog
          body:
            scripts:
              - angular
              - angular_animate
              - angular_resource
              - angular_sanitize
